### ISSUE TITLE
Fresco not coexisting with GDX

### ISSUE THREAD

**Issue by xiangdev** [facebook/fresco#324]
With fresco 0.5.0 I found that images are not displayed on certain Samsung devices with Android 5.0.2.

On similar devices such as LG Nexus 4 (Android 5.1) or Sony Xperia Z1 (Android 5.0.2) images are loaded just fine with the same app (exactly the same apk binary).
This issue is not reproducible on Samsung Galaxy S4 (Android 4.4.2) or older devices either.

I could not see much debug info rather than this info log:
05-28 14:38:04.781  13750-14917/<appname> I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.facebook.imagepipeline.memory.NativeMemoryChunk>
05-28 14:38:04.791  13750-20869/<appname> I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.facebook.imagepipeline.memory.NativeMemoryChunk>

Following is the spec for one of the phones:

Galaxy S6 edge
SM-G925I
5.0.2

Please let me know if there is any other information I can provide to help investigate. Thanks.

**Comment by TarangS** [comment]
Thanks for reporting. We are aware of this and it would be fixed in the next release.

**Comment by tyronen** [comment]
There was a known problem with the S6's 64-bit hardware that has been fixed in v0.5.1.

**Comment by Laces** [comment]
Facing the same problem with com.facebook.fresco:fresco:0.5.2

Rejecting re-init on previously-failed class java.lang.Class\<com.facebook.imagepipeline.memory.NativeMemoryChunk>

Any ideas how to fix this? 
I have tried on a Nexus 5, Android 5.1.1 and HTC one X, Android 4.2.2, with no success, nothing appears, except the placeholder.

Alsaw I have tried with version 0.5.0 and 0.5.1 but nothing changed.

**Comment by Laces** [comment]
I have created a separate activity for this to try out, and now the "Rejecting re-init..." message is missing, but there is another message: W/dalvikvm﹕ Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/facebook/imagepipeline/memory/NativeMemoryChunk; and the image is still missing.

**Comment by tyronen** [comment]
Laces, your issue is different from the original as it occurs on non-S6 devices.

What kind of images fail to appear?

**Comment by Laces** [comment]
Then sorry to post in the wrong thread.
I have tried with the tutorial found here: http://frescolib.org/docs/getting-started.html
Everything was exactly the same, the url was: https://raw.githubusercontent.com/facebook/fresco/gh-pages/static/fresco-logo.png

Tomorrow I'll start a new & clean project to try this out...

**Comment by Laces** [comment]
I think I have found the problem, 
I wanted to use Fresco with libGDX on Android, and in my gradle file I have this:


// needed to add JNI shared libraries to APK when compiling on CLI
tasks.withType(com.android.build.gradle.tasks.PackageApplication) { pkgTask ->
    pkgTask.jniFolders = new HashSet<File>()
    pkgTask.jniFolders.add(new File(projectDir, 'libs'))
}

If I remove these lines, the Fresco works, but the GDX doesn't...
Do you have any idea how can I fix this?
Thanks!

**Comment by JorisBolsens** [comment]
Running into the same issue, however not using the GDX library or an S6.

I am running on a nexus 6, more details in #746

**Comment by JorisBolsens** [comment]
Is there some workaround I can try so it will work? because right now no images are loading at all from the network.

**Comment by githubdoramon** [comment]
I was having this problem, and is discovered that the first image Fresco was trying to load had a invalid url "/statix/img/bla.jpg" instead of "https://mydomain.com/statix/img/bla.jpg" and that was blocking all other fresco attempts to load anything

**Comment by dmitriigaidarji** [comment]
Same problem on sumsung galaxy s4 i9295

**Comment by peterchappy** [comment]
Anyone have any luck?

**Comment by aslamhirani** [comment]
@githubdoramon - Thanks. Your suggestion helped me to solve the issue.

**Comment by knitterb-razzle** [comment]
This seems like it's still an issue with Fresco 0.9.0 and the latest GMS (google-services).  Genymotion Nexus 5 with API21 5.0.0.

**Comment by erikandre** [comment]
No new reports of this for more than a year, closing issue.
